image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean install
    command: docker-compose up -d && ./mvnw spring-boot:run

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - vscjava.vscode-spring-boot-dashboard
    - ms-azuretools.vscode-docker
