image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup MySQL
    init: |
      # Install MySQL properly
      sudo apt-get update
      sudo apt-get install -y mysql-server
      sudo mkdir -p /var/run/mysqld
      sudo chown -R gitpod:gitpod /var/run/mysqld
      sudo service mysql start
      mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY ''; FLUSH PRIVILEGES;"
      mysql -uroot -e "CREATE DATABASE IF NOT EXISTS mydatabase;"
    openIn: bottom

  - name: Run Spring Boot
    command: |
      ./mvnw spring-boot:run
    openIn: bottom

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore